spring.application.name=API RFC
spring.datasource.url=jdbc:h2:mem:eg_21_rfc
spring.datasource.username=eglobal_user
spring.datasource.password=eglobal_pass
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
logging.level.org.springframework.web=debug